#!/bin/bash
# parallel job for SLURM scheduler

# requested comptational resources
#SBATCH -n PROC
#SBATCH -N NODE
#SBATCH -J NAME
#SBATCH -t TIME

# option for sending email updates
# #SBATCH --mail-type=begin
# #SBATCH --mail-type=end
# #SBATCH --mail-user=NETID@princeton.edu

# load requisite modules
module purge
module load intel/19.1
module load openmpi/intel-19.1/4.1.0

# cd to working directory and execute the code
cd WORKING_DIRECTORY
srun ./CODE < SIM_DIRECTORY 


